//! Practice Coach — Text-to-Speech engine using Piper TTS.
//!
//! Downloads the Piper binary + voice models to the app data directory.
//! Speech is generated by invoking `piper` as a subprocess, writing a WAV
//! file, then playing it with `afplay` (macOS). The metronome volume is
//! dimmed during speech (handled by the tts_speak command).

use std::path::PathBuf;
use std::process::Command;
use std::sync::{Arc, Mutex};

/// Available voice identifiers — maps to downloaded .onnx files.
pub const VOICES: &[(&str, &str)] = &[
    ("lessac", "Lessac"),   // Clear, expressive (default)
    ("amy", "Amy"),         // Female, warm
    ("ryan", "Ryan"),       // Male, deeper
];

/// Shared TTS engine state.
pub type SharedTts = Arc<Mutex<TtsEngine>>;

pub fn create_shared_tts() -> SharedTts {
    Arc::new(Mutex::new(TtsEngine::new()))
}

pub struct TtsEngine {
    voice: String,
    models_dir: Option<PathBuf>,
    speaking: bool,
}

impl TtsEngine {
    pub fn new() -> Self {
        TtsEngine {
            voice: "lessac".to_string(),
            models_dir: None,
            speaking: false,
        }
    }

    /// Set the models directory (called once after app init).
    pub fn set_models_dir(&mut self, dir: PathBuf) {
        self.models_dir = Some(dir);
    }

    pub fn set_voice(&mut self, voice: &str) {
        self.voice = voice.to_string();
    }

    pub fn get_voice(&self) -> &str {
        &self.voice
    }

    pub fn is_speaking(&self) -> bool {
        self.speaking
    }

    /// Check if Piper binary and the selected voice model are available.
    pub fn is_ready(&self) -> bool {
        if let Some(dir) = &self.models_dir {
            let piper = dir.join("piper").join("piper");
            let model = dir.join("voice").join(format!("en_US-{}-medium.onnx", self.voice));
            piper.exists() && model.exists()
        } else {
            false
        }
    }

    /// Speak text using Piper TTS.
    /// Generates a WAV file then plays it with afplay.
    /// Blocks until playback is complete — call from a background thread.
    pub fn speak(&mut self, text: &str) -> Result<(), String> {
        let dir = self.models_dir.as_ref().ok_or("Models directory not set")?;
        let piper_bin = dir.join("piper").join("piper");
        let model_path = dir.join("voice").join(format!("en_US-{}-medium.onnx", self.voice));

        if !piper_bin.exists() {
            return self.speak_fallback(text);
        }
        if !model_path.exists() {
            return self.speak_fallback(text);
        }

        self.speaking = true;

        // Generate WAV to a temp file
        let tmp_wav = std::env::temp_dir().join("yames_tts.wav");

        let piper_result = Command::new(&piper_bin)
            .arg("--model")
            .arg(&model_path)
            .arg("--output_file")
            .arg(&tmp_wav)
            .stdin(std::process::Stdio::piped())
            .stdout(std::process::Stdio::null())
            .stderr(std::process::Stdio::null())
            .spawn()
            .and_then(|mut child| {
                if let Some(mut stdin) = child.stdin.take() {
                    use std::io::Write;
                    let _ = stdin.write_all(text.as_bytes());
                }
                child.wait()
            });

        match piper_result {
            Ok(status) if status.success() && tmp_wav.exists() => {
                // Play the WAV file
                let play_result = Command::new("afplay")
                    .arg(&tmp_wav)
                    .output();

                let _ = std::fs::remove_file(&tmp_wav);
                self.speaking = false;

                match play_result {
                    Ok(output) if output.status.success() => Ok(()),
                    Ok(output) => Err(format!("afplay failed: {}", String::from_utf8_lossy(&output.stderr))),
                    Err(e) => Err(format!("afplay error: {e}")),
                }
            }
            Ok(status) => {
                self.speaking = false;
                let _ = std::fs::remove_file(&tmp_wav);
                Err(format!("piper exited with {status}"))
            }
            Err(e) => {
                self.speaking = false;
                Err(format!("piper error: {e}"))
            }
        }
    }

    /// Fallback to macOS `say` if Piper isn't available.
    fn speak_fallback(&mut self, text: &str) -> Result<(), String> {
        self.speaking = true;
        let result = Command::new("say")
            .arg("-r")
            .arg("175")
            .arg(text)
            .output()
            .map_err(|e| format!("TTS failed: {e}"));

        self.speaking = false;

        match result {
            Ok(output) if output.status.success() => Ok(()),
            Ok(output) => Err(format!(
                "say exited with {}: {}",
                output.status,
                String::from_utf8_lossy(&output.stderr)
            )),
            Err(e) => Err(e),
        }
    }

    /// List available voices (only those with downloaded models).
    pub fn list_available_voices(&self) -> Vec<(String, String)> {
        let dir = match &self.models_dir {
            Some(d) => d,
            None => return Vec::new(),
        };
        let voice_dir = dir.join("voice");
        VOICES
            .iter()
            .filter(|(id, _)| voice_dir.join(format!("en_US-{id}-medium.onnx")).exists())
            .map(|(id, name)| (id.to_string(), name.to_string()))
            .collect()
    }
}

/// Piper binary download URL for the current platform.
pub fn piper_binary_url() -> &'static str {
    if cfg!(target_arch = "aarch64") {
        "https://github.com/rhasspy/piper/releases/download/2023.11.14-2/piper_macos_aarch64.tar.gz"
    } else {
        "https://github.com/rhasspy/piper/releases/download/2023.11.14-2/piper_macos_x64.tar.gz"
    }
}

/// Voice model download URLs (model_id, onnx_url, json_url).
pub fn voice_model_urls() -> Vec<(&'static str, &'static str, &'static str)> {
    vec![
        (
            "lessac",
            "https://huggingface.co/rhasspy/piper-voices/resolve/main/en/en_US/lessac/medium/en_US-lessac-medium.onnx",
            "https://huggingface.co/rhasspy/piper-voices/resolve/main/en/en_US/lessac/medium/en_US-lessac-medium.onnx.json",
        ),
        (
            "amy",
            "https://huggingface.co/rhasspy/piper-voices/resolve/main/en/en_US/amy/medium/en_US-amy-medium.onnx",
            "https://huggingface.co/rhasspy/piper-voices/resolve/main/en/en_US/amy/medium/en_US-amy-medium.onnx.json",
        ),
        (
            "ryan",
            "https://huggingface.co/rhasspy/piper-voices/resolve/main/en/en_US/ryan/medium/en_US-ryan-medium.onnx",
            "https://huggingface.co/rhasspy/piper-voices/resolve/main/en/en_US/ryan/medium/en_US-ryan-medium.onnx.json",
        ),
    ]
}
